<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginNewManuscriptResume</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-03-27T10:28:02</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c9b522d2-676a-4476-a82b-7656686190c7</testSuiteGuid>
   <testCaseLink>
      <guid>80073546-f048-4282-a7ab-5596415a6405</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign In/Sign In flow</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e818a000-1434-4565-9664-6d2992456762</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9ab62a4-f041-4f4f-9e59-0dcb31fc00e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Add new manuscript/Add a new manuscript</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30a84231-84ba-44cb-9eec-26ad7d97acd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68ae01ba-31a5-4819-aa48-3031d89305ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ac440cf-7be0-47d5-acb5-dc9a9f2bba0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Resume Manuscript/Resume submission Redirect</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
