<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginNewManuscript</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-03-27T10:26:57</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0bd4d69a-2e5f-4628-a1f6-58318bc57b05</testSuiteGuid>
   <testCaseLink>
      <guid>c0a987c5-6a97-44c2-b0b9-4642a4a6b0da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign In/Sign In flow</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e818a000-1434-4565-9664-6d2992456762</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>725bd536-5fee-431d-bd1e-7ec5f3a21912</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Add new manuscript/Add a new manuscript</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30a84231-84ba-44cb-9eec-26ad7d97acd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68ae01ba-31a5-4819-aa48-3031d89305ba</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
