<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>users</name>
   <tag></tag>
   <elementGuidId>fc06cfc7-c7e0-449f-b85c-d7c1f34f21c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[data-test=&quot;card-users&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eXNvrr hVBWZK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-cmTdod hZxvxw&quot;]/div[@class=&quot;sc-dyGzUR bQYZEl&quot;]/div[@class=&quot;sc-drKuOJ fmUpkt&quot;]/div[@class=&quot;sc-hIVACf dydoGZ&quot;]/div[@class=&quot;sc-gVyKpa knVGhf&quot;]/div[@class=&quot;sc-eXNvrr hVBWZK&quot;]</value>
   </webElementProperties>
</WebElementEntity>
