<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status</name>
   <tag></tag>
   <elementGuidId>42de3db4-4bea-401e-8272-331ed40b55ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-kkGfuU ggkpPG</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose in the list▼</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jwKygS eXvhap&quot;]/div[@class=&quot;sc-gRnDUn bJTbsv&quot;]/div[@class=&quot;sc-cmjSyW dlKXSW&quot;]/div[1]/div[@class=&quot;sc-kaNhvL kWSDv&quot;]/div[@class=&quot;sc-jtggT cyvQev&quot;]/div[@class=&quot;sc-ebFjAB jxmaG&quot;]/div[@class=&quot;sc-jKVCRD bnbeWW&quot;]/div[@class=&quot;sc-eNQAEJ AwxHh&quot;]/div[@class=&quot;sc-jWBwVP gkntHJ&quot;]/button[@class=&quot;sc-kkGfuU ggkpPG&quot;]</value>
   </webElementProperties>
</WebElementEntity>
